@host=https://localhost:7299

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YWY1YTE2My1kOTlkLTQyMDItOWIyNC0xNTJiMWJlYzM4ZjgiLCJnaXZlbl9uYW1lIjoiQWRhbiIsImZhbWlseV9uYW1lIjoiTXVyaWRpIiwianRpIjoiODRhMTYxOWEtNzYwZC00NWM2LTkyZjEtNDM3ZDdmOWU2NTllIiwiZXhwIjoxNjgwMDk1MzUxLCJpc3MiOiJUcmFpbFRyZWsiLCJhdWQiOiJUcmFpbFRyZWsifQ.c3YDL3oNxHYo63VyPiAZGhux4SqtZldTN3iM9IPpnrw